/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import React from 'react';
import { MutableRefObject } from 'react';
import { useImperativeHandle } from 'react';
import { useEffect } from 'react';
import { GLTFResult } from './types';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

const Lightsaber = React.forwardRef(
  ({ ...props }: JSX.IntrinsicElements['group'], ref) => {
    const meshRef = useRef<THREE.Group>();
    const { nodes, materials } = useGLTF(
      '/public/assets/lightsaber/lightsaber.gltf'
    ) as GLTFResult;

    let mesh: THREE.Group;

    useEffect(() => {
      if (meshRef.current) {
        mesh = meshRef.current as THREE.Group;
      }
    }, [meshRef]);

    useImperativeHandle(
      ref,
      () => {
        if (meshRef.current) {
          mesh = meshRef.current as THREE.Group;
        }
        return mesh;
      },
      [meshRef]
    );
    return (
      <group
        ref={meshRef as MutableRefObject<THREE.Group>}
        {...props}
        dispose={null}
      >
        <group name='Root_Scene'>
          <group name='RootNode'>
            <group
              name='Cylinder'
              position={[0, 0.33, 2.35]}
              rotation={[-Math.PI, 0, Math.PI / 2]}
              scale={[18.09, 18.09, 41.17]}
            >
              <mesh
                castShadow
                name='Cylinder_1'
                geometry={nodes.Cylinder_1.geometry}
                material={materials['Material.010']}
              />
              <mesh
                castShadow
                name='Cylinder_2'
                geometry={nodes.Cylinder_2.geometry}
                material={materials['Material.008']}
              />
              <mesh
                castShadow
                name='Cylinder_3'
                geometry={nodes.Cylinder_3.geometry}
                material={materials['Material.006']}
              />
              <mesh rotation={[1.5, 0, 0]} position={[0, 0.005, 0.07]}>
                <capsuleGeometry args={[0.007, 0.2, 100, 100]} />
                <meshBasicMaterial color={'red'} />
              </mesh>
            </group>
          </group>
        </group>
      </group>
    );
  }
);

useGLTF.preload('/public/assets/lightsaber/lightsaber.gltf');

export default Lightsaber;
